word_list = [
    {"word": "abandon", "meanings": ["버리다", "떠나다", "포기하다", "유기하다"], "correct_meaning": "버리다"},
    {"word": "benevolent", "meanings": ["자비로운", "친절한", "인자한", "호의적인"], "correct_meaning": "자비로운"},
    {"word": "candid", "meanings": ["솔직한", "숨김없는", "정직한", "거리낌 없는"], "correct_meaning": "솔직한"},
    {"word": "diligent", "meanings": ["근면한", "부지런한", "성실한", "열심인"], "correct_meaning": "근면한"},
    {"word": "eloquent", "meanings": ["웅변의", "유창한", "설득력 있는", "표현력이 좋은"], "correct_meaning": "유창한"},
    {"word": "frugal", "meanings": ["검소한", "절약하는", "검약한", "알뜰한"], "correct_meaning": "검소한"},
    {"word": "genuine", "meanings": ["진짜의", "순수한", "진정한", "진솔한"], "correct_meaning": "진짜의"},
    {"word": "humble", "meanings": ["겸손한", "소박한", "보잘것없는", "미천한"], "correct_meaning": "겸손한"},
    {"word": "innovative", "meanings": ["혁신적인", "창의적인", "새로운", "독창적인"], "correct_meaning": "혁신적인"},
    {"word": "judicious", "meanings": ["현명한", "신중한", "분별 있는", "사려 깊은"], "correct_meaning": "현명한"},
    {"word": "keen", "meanings": ["날카로운", "예리한", "열망하는", "열심인"], "correct_meaning": "날카로운"},
    {"word": "lucid", "meanings": ["명료한", "투명한", "이해하기 쉬운", "맑은"], "correct_meaning": "명료한"},
    {"word": "meticulous", "meanings": ["세심한", "꼼꼼한", "주의 깊은", "철저한"], "correct_meaning": "세심한"},
    {"word": "noble", "meanings": ["고귀한", "귀족의", "고상한", "고결한"], "correct_meaning": "고귀한"},
    {"word": "optimistic", "meanings": ["낙관적인", "긍정적인", "희망적인", "밝은"], "correct_meaning": "낙관적인"},
    {"word": "prudent", "meanings": ["신중한", "현명한", "조심스러운", "분별 있는"], "correct_meaning": "신중한"},
    {"word": "resilient", "meanings": ["회복력 있는", "탄력 있는", "강인한", "유연한"], "correct_meaning": "회복력 있는"},
    {"word": "sincere", "meanings": ["진실한", "성실한", "진정한", "솔직한"], "correct_meaning": "진실한"},
    {"word": "tenacious", "meanings": ["끈질긴", "집요한", "고집 센", "완강한"], "correct_meaning": "끈질긴"},
    {"word": "versatile", "meanings": ["다재다능한", "다용도의", "변화무쌍한", "적응력이 있는"], "correct_meaning": "다재다능한"},
    {"word": "witty", "meanings": ["재치 있는", "기지 있는", "유머러스한", "영리한"], "correct_meaning": "재치 있는"},
    {"word": "zealous", "meanings": ["열성적인", "열심인", "열광적인", "열렬한"], "correct_meaning": "열성적인"},
    {"word": "ambiguous", "meanings": ["모호한", "애매한", "불분명한", "두 가지 뜻이 있는"], "correct_meaning": "모호한"},
    {"word": "abundant", "meanings": ["풍부한", "많은", "충분한", "넘치는"], "correct_meaning": "풍부한"},
    {"word": "adversary", "meanings": ["적", "상대방", "경쟁자", "반대자"], "correct_meaning": "적"},
    {"word": "advocate", "meanings": ["옹호하다", "지지하다", "주장하다", "변호하다"], "correct_meaning": "옹호하다"},
    {"word": "affable", "meanings": ["친근한", "상냥한", "다정한", "호감이 가는"], "correct_meaning": "친근한"},
    {"word": "alleviate", "meanings": ["완화하다", "덜어주다", "경감하다", "누그러뜨리다"], "correct_meaning": "완화하다"},
    {"word": "ambivalent", "meanings": ["양면감정의", "모순된", "애매한", "확신이 없는"], "correct_meaning": "양면감정의"},
    {"word": "articulate", "meanings": ["명확히 표현하다", "또렷하게 말하다", "분명한", "유창한"], "correct_meaning": "명확히 표현하다"},
    {"word": "austere", "meanings": ["엄격한", "금욕적인", "간소한", "소박한"], "correct_meaning": "엄격한"},
    {"word": "benign", "meanings": ["온화한", "친절한", "무해한", "양성의"], "correct_meaning": "온화한"},
    {"word": "capricious", "meanings": ["변덕스러운", "기분파의", "예측할 수 없는", "변화무쌍한"], "correct_meaning": "변덕스러운"},
    {"word": "coherent", "meanings": ["일관성 있는", "논리적인", "명확한", "체계적인"], "correct_meaning": "일관성 있는"},
    {"word": "compelling", "meanings": ["설득력 있는", "강제적인", "매력적인", "압도적인"], "correct_meaning": "설득력 있는"},
    {"word": "complacent", "meanings": ["자만하는", "안주하는", "현실에 안주하는", "만족해하는"], "correct_meaning": "자만하는"},
    {"word": "concise", "meanings": ["간결한", "간명한", "요약된", "압축된"], "correct_meaning": "간결한"},
    {"word": "congenial", "meanings": ["마음에 맞는", "친화적인", "즐거운", "어울리는"], "correct_meaning": "마음에 맞는"},
    {"word": "contemplate", "meanings": ["숙고하다", "명상하다", "고려하다", "바라보다"], "correct_meaning": "숙고하다"},
    {"word": "cordial", "meanings": ["따뜻한", "진심어린", "친근한", "정중한"], "correct_meaning": "따뜻한"},
    {"word": "credible", "meanings": ["믿을 만한", "신빙성 있는", "그럴듯한", "신뢰할 수 있는"], "correct_meaning": "믿을 만한"},
    {"word": "decisive", "meanings": ["결정적인", "단호한", "결단력 있는", "확실한"], "correct_meaning": "결정적인"},
    {"word": "defer", "meanings": ["연기하다", "미루다", "존경하다", "따르다"], "correct_meaning": "연기하다"},
    {"word": "deliberate", "meanings": ["신중한", "고의적인", "의도적인", "숙고하다"], "correct_meaning": "신중한"},
    {"word": "diligent", "meanings": ["부지런한", "근면한", "성실한", "열심인"], "correct_meaning": "부지런한"},
    {"word": "discern", "meanings": ["분별하다", "구별하다", "알아보다", "인식하다"], "correct_meaning": "분별하다"},
    {"word": "doctrine", "meanings": ["교리", "학설", "원칙", "주의"], "correct_meaning": "교리"},
    {"word": "dormant", "meanings": ["잠자는", "휴면상태의", "비활성의", "잠복된"], "correct_meaning": "잠자는"},
    {"word": "earnest", "meanings": ["진지한", "열심인", "성실한", "간절한"], "correct_meaning": "진지한"},
    {"word": "elaborate", "meanings": ["정교한", "복잡한", "자세히 설명하다", "공들인"], "correct_meaning": "정교한"},
    {"word": "endorse", "meanings": ["지지하다", "승인하다", "보증하다", "찬성하다"], "correct_meaning": "지지하다"},
    {"word": "enhance", "meanings": ["향상시키다", "증진하다", "강화하다", "높이다"], "correct_meaning": "향상시키다"},
    {"word": "enigma", "meanings": ["수수께끼", "불가사의", "미스터리", "수수께끼 같은 사람"], "correct_meaning": "수수께끼"},
    {"word": "ephemeral", "meanings": ["일시적인", "덧없는", "단명한", "잠깐의"], "correct_meaning": "일시적인"},
    {"word": "ethical", "meanings": ["윤리적인", "도덕적인", "올바른", "양심적인"], "correct_meaning": "윤리적인"},
    {"word": "exemplary", "meanings": ["모범적인", "훌륭한", "본보기가 되는", "전형적인"], "correct_meaning": "모범적인"},
    {"word": "explicit", "meanings": ["명시적인", "분명한", "노골적인", "명확한"], "correct_meaning": "명시적인"},
    {"word": "feasible", "meanings": ["실행 가능한", "현실적인", "타당한", "가능한"], "correct_meaning": "실행 가능한"},
    {"word": "fortitude", "meanings": ["용기", "인내력", "불굴의 정신", "강인함"], "correct_meaning": "용기"},
    {"word": "gratitude", "meanings": ["감사", "고마움", "감사하는 마음", "고마워하는 마음"], "correct_meaning": "감사"},
    {"word": "harmonious", "meanings": ["조화로운", "화목한", "일치하는", "평화로운"], "correct_meaning": "조화로운"},
    {"word": "imperative", "meanings": ["필수적인", "긴급한", "명령적인", "중요한"], "correct_meaning": "필수적인"},
    {"word": "implicit", "meanings": ["암시적인", "함축적인", "절대적인", "내재된"], "correct_meaning": "암시적인"},
    {"word": "inconspicuous", "meanings": ["눈에 띄지 않는", "두드러지지 않는", "겸손한", "조용한"], "correct_meaning": "눈에 띄지 않는"},
    {"word": "indispensable", "meanings": ["없어서는 안 될", "필수의", "꼭 필요한", "중요한"], "correct_meaning": "없어서는 안 될"},
    {"word": "inevitable", "meanings": ["피할 수 없는", "불가피한", "필연적인", "운명적인"], "correct_meaning": "피할 수 없는"},
    {"word": "integrity", "meanings": ["성실성", "정직", "완전성", "고결함"], "correct_meaning": "성실성"},
    {"word": "intricate", "meanings": ["복잡한", "정교한", "얽힌", "세밀한"], "correct_meaning": "복잡한"},
    {"word": "jeopardize", "meanings": ["위험에 빠뜨리다", "위태롭게 하다", "해치다", "손상시키다"], "correct_meaning": "위험에 빠뜨리다"},
    {"word": "lenient", "meanings": ["관대한", "너그러운", "온화한", "자비로운"], "correct_meaning": "관대한"},
    {"word": "magnitude", "meanings": ["크기", "규모", "중요성", "정도"], "correct_meaning": "크기"},
    {"word": "moderate", "meanings": ["온건한", "적당한", "중간의", "절제하다"], "correct_meaning": "온건한"},
    {"word": "profound", "meanings": ["깊은", "심오한", "깊이 있는", "근본적인"], "correct_meaning": "깊은"},
    {"word": "pragmatic", "meanings": ["실용적인", "현실적인", "실제적인", "실무적인"], "correct_meaning": "실용적인"},
    {"word": "prestigious", "meanings": ["명망 있는", "권위 있는", "존경받는", "일류의"], "correct_meaning": "명망 있는"},
    {"word": "prominent", "meanings": ["저명한", "유명한", "두드러진", "탁월한"], "correct_meaning": "저명한"},
    {"word": "prosperous", "meanings": ["번영하는", "성공한", "풍요로운", "잘사는"], "correct_meaning": "번영하는"},
    {"word": "rational", "meanings": ["합리적인", "이성적인", "논리적인", "타당한"], "correct_meaning": "합리적인"},
    {"word": "reciprocal", "meanings": ["상호의", "서로의", "호혜적인", "상호간의"], "correct_meaning": "상호의"},
    {"word": "reluctant", "meanings": ["꺼리는", "마지못한", "주저하는", "내키지 않는"], "correct_meaning": "꺼리는"},
    {"word": "remote", "meanings": ["먼", "외딴", "희박한", "멀리 떨어진"], "correct_meaning": "먼"},
    {"word": "rigorous", "meanings": ["엄격한", "엄밀한", "철저한", "혹독한"], "correct_meaning": "엄격한"},
    {"word": "robust", "meanings": ["강건한", "튼튼한", "활기찬", "견고한"], "correct_meaning": "강건한"},
    {"word": "scrutinize", "meanings": ["면밀히 조사하다", "자세히 살펴보다", "검토하다", "분석하다"], "correct_meaning": "면밀히 조사하다"},
    {"word": "shrewd", "meanings": ["영리한", "약삭빠른", "기민한", "날카로운"], "correct_meaning": "영리한"},
    {"word": "skeptical", "meanings": ["회의적인", "의심하는", "비판적인", "불신하는"], "correct_meaning": "회의적인"},
    {"word": "spontaneous", "meanings": ["자발적인", "즉흥적인", "자연스러운", "순간적인"], "correct_meaning": "자발적인"},
    {"word": "substantial", "meanings": ["상당한", "실질적인", "중요한", "든든한"], "correct_meaning": "상당한"},
    {"word": "subtle", "meanings": ["미묘한", "섬세한", "교묘한", "은근한"], "correct_meaning": "미묘한"},
    {"word": "superficial", "meanings": ["표면적인", "피상적인", "얕은", "겉치레의"], "correct_meaning": "표면적인"},
    {"word": "systematic", "meanings": ["체계적인", "조직적인", "규칙적인", "계획적인"], "correct_meaning": "체계적인"},
    {"word": "tangible", "meanings": ["유형의", "실체가 있는", "명확한", "만질 수 있는"], "correct_meaning": "유형의"},
    {"word": "transparent", "meanings": ["투명한", "명확한", "솔직한", "공개적인"], "correct_meaning": "투명한"},
    {"word": "trivial", "meanings": ["사소한", "하찮은", "중요하지 않은", "시시한"], "correct_meaning": "사소한"},
    {"word": "ultimate", "meanings": ["최종의", "궁극적인", "최고의", "근본적인"], "correct_meaning": "최종의"},
    {"word": "unanimous", "meanings": ["만장일치의", "전원 일치의", "한목소리의", "일치된"], "correct_meaning": "만장일치의"},
    {"word": "unprecedented", "meanings": ["전례 없는", "미증유의", "새로운", "처음의"], "correct_meaning": "전례 없는"},
    {"word": "valid", "meanings": ["유효한", "타당한", "근거가 있는", "정당한"], "correct_meaning": "유효한"},
    {"word": "vivid", "meanings": ["생생한", "선명한", "강렬한", "뚜렷한"], "correct_meaning": "생생한"},
    {"word": "vulnerable", "meanings": ["취약한", "상처받기 쉬운", "연약한", "무력한"], "correct_meaning": "취약한"}
]

# 단어 총 개수 확인
total_words = len(word_list)
print(f"총 {total_words}개의 단어가 있습니다.")